apiVersion: v1
automountServiceAccountToken: false
imagePullSecrets:
- name: bct-service-registry
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: bct-service
  namespace: bct-service
