name: CI

on:
  push:
    branches:
      - main
      - '!dependabot/**'
    tags:
      - '**'
  pull_request: []

jobs:

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Build
        run: |
          set -o errexit
          set -o nounset
          set -o pipefail
          
          make build

      - name: Test
        run: make test

  release:
    needs:
      - unit
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - uses: actions/checkout@v4
    - name: Additional tag
      id: additional_tag
      env:
        GITHUB_TOKEN: ${{ secrets.TAGGING }}
      run: |
        set -o errexit
        set -o nounset
        set -o pipefail
        
        git tag test/${{ steps.get_version.outputs.VERSION }}
        git push origin test/${{ steps.get_version.outputs.VERSION }}
