name: CI

on:
  push:
    branches:
      - main
      - '!dependabot/**'
    tags:
      - '**'
  pull_request: []

permissions:
  contents: write

jobs:

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Build
        run: |
          set -o errexit
          set -o nounset
          set -o pipefail
          
          make build

      - name: Test
        run: make test

  release:
    needs:
      - unit
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - uses: actions/checkout@v5

    - name: Create and push new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git tag release/${{ steps.get_version.outputs.VERSION }}
        git push origin release/${{ steps.get_version.outputs.VERSION }}
